### ISSUE TITLE
Linux crash on map load

### ISSUE THREAD

**Issue by ChillerDragon** [ZillyWoods/ZillyWoods#42]
```
[2020-01-31 22:17:19][datafile]: loading done. datafile='downloadedmaps/NUT_hardcore_bestof_f63e579bd5b6a66fc71e96454a665393b2edc6f48aa22f47fb280a7767cb7556.map'
[2020-01-31 22:17:19][client]: loaded map 'downloadedmaps/NUT_hardcore_bestof_f63e579bd5b6a66fc71e96454a665393b2edc6f48aa22f47fb280a7767cb7556.map'
[2020-01-31 22:17:19][client/network]: loading done
[2020-01-31 22:17:19][datafile]: loading data index=5 size=3693 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=7 size=229 uncompressed=72390
[2020-01-31 22:17:19][datafile]: loading data index=11 size=741 uncompressed=217170
[2020-01-31 22:17:19][datafile]: loading data index=9 size=272 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=4 size=884 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=6 size=163 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=8 size=163 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=10 size=163 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=12 size=2760 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=13 size=2752 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=14 size=349 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=15 size=3943 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=16 size=2532 uncompressed=144780
[2020-01-31 22:17:19][datafile]: loading data index=0 size=27 uncompressed=19
[2020-01-31 22:17:19][datafile]: loading data index=2 size=255749 uncompressed=4194304
*** stack smashing detected ***: <unknown> terminated

Thread 1 "zillywoods" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6f2f535 in __GI_abort () at abort.c:79
#2  0x00007ffff6f86508 in __libc_message (action=<optimized out>, fmt=fmt@entry=0x7ffff709107b "*** %s ***: %s terminated\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff701780d in __GI___fortify_fail_abort (need_backtrace=need_backtrace@entry=false, msg=msg@entry=0x7ffff7091059 "stack smashing detected") at fortify_fail.c:28
#4  0x00007ffff70177c2 in __stack_chk_fail () at stack_chk_fail.c:29
#5  0x00005555555dc9ce in CMapLayers::LoadEnvPoints(CLayers const*, array<CEnvPoint, allocator_default<CEnvPoint> >&) [clone .constprop.38] ()
#6  0x00005555555dca00 in CMapLayers::OnMapLoad() ()
#7  0x000055555562da2b in CGameClient::OnConnected() ()
#8  0x000055555559ffbd in CClient::ProcessServerPacket(CNetChunk*) ()
#9  0x00005555555a1e95 in CClient::PumpNetwork() ()
#10 0x00005555555a1fac in CClient::Update() ()
#11 0x00005555555a2ed5 in CClient::Run() ()
#12 0x0000555555592fd1 in main ()
```

**Comment by ChillerDragon** [comment]
I blame the map tho.
